name: Github Action for Octave
on: [push, pull_request]
jobs:
  octave_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7
    - run: |
        sudo apt-get install octave octave-control
    - run: octave --eval "ctpf"
      working-directory: ./src/ctpf/
    - run: octave --eval "lcl"
      working-directory: ./src/lcl/
    - run: octave --eval "series_lc"
      working-directory: ./src/series/
